[phases.setup]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npx prisma db push && NODE_ENV=production node .next/standalone/server.js"
