[phases.setup]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npx prisma db push --skip-generate 2>/dev/null; node .next/standalone/server.js"
